name: Check Changelog and Version

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: flotiq/check-changelog-and-version@v1.1.1
        with:
          changelog_file: CHANGELOG.md
          version_file: package.json